-- Auteur 初始化 schema(单一基线)
-- 包含 24 张业务表 + app_config 默认行
-- 预设种子(lifecopy / freeform)由 V2/V3 Java migration 在初始化后注入

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `app_config` (
  `config_key` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '形如 auteur.llm.api-key',
  `config_value` text COLLATE utf8mb4_unicode_ci COMMENT '运行时实际值;NULL/空 = 走 yml 兜底',
  `description` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'UI 一句话说明',
  `is_secret` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否敏感(UI 默认 mask)',
  `category` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'llm / tos / voice / bgm',
  `sort_order` int NOT NULL DEFAULT '0',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`config_key`),
  KEY `idx_app_config_category` (`category`,`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='UI 可编辑的运行时配置 — yml 兜底,DB 覆盖';
CREATE TABLE `bgm_track` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `jamendo_id` bigint NOT NULL COMMENT 'Jamendo 曲目 id, 全局唯一',
  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `artist_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `duration_seconds` int DEFAULT NULL,
  `audio_url` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Jamendo 直链 mp3, 下载源',
  `preview_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '30s 试听片段, 前端 audio 控件用',
  `album_image_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `license_type` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'CC-BY / CC-BY-SA / CC0 等',
  `mood_tag` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '本曲首次匹配上的 mood, 6 词表',
  `local_path` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '已下载到 ./storage/bgm/{jamendoId}.mp3 后回填',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bgm_jamendo` (`jamendo_id`),
  KEY `idx_bgm_mood` (`mood_tag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Jamendo 曲库缓存';
CREATE TABLE `brand_identity` (
  `id` bigint NOT NULL,
  `brand_name` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '账号显示名(如「历史密档」),封面右下角主文字',
  `author_name` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '抖音/快手主页的 @xxx,封面 @ 角标',
  `logo_data_url` mediumtext COLLATE utf8mb4_unicode_ci COMMENT 'data:image/png;base64,xxx;NULL=只渲文字不画 logo',
  `primary_color` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '#0F1F33',
  `secondary_color` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '#C9A961' COMMENT 'logo 圆框描边色 / 副色',
  `accent_color` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '#E04A2A',
  `bg_color` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '#F5EFE0',
  `title_font` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '"Noto Serif SC", "PingFang SC", serif',
  `default_template_id` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'bottom-caption',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='账号品牌包(单行,id=1),驱动封面渲染右下角账号标志';
CREATE TABLE `cover_asset` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `script_id` bigint NOT NULL,
  `ratio` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '3:4 | 4:3 | 16:9',
  `width` int NOT NULL,
  `height` int NOT NULL,
  `template_id` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'bottom-caption|split-vertical|diagonal|minimal',
  `title_text` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hero_image_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'storyboard final 图 URL,渲染时带入',
  `file_url` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '/api/files/cover/<filename>.png',
  `file_size_bytes` bigint DEFAULT NULL,
  `is_final` tinyint(1) NOT NULL DEFAULT '0',
  `run_id` bigint DEFAULT NULL COMMENT '哪次 PipelineRun 产出',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_cover_script_created` (`script_id`,`created_at`),
  KEY `idx_cover_run` (`run_id`),
  CONSTRAINT `fk_cover_asset_script` FOREIGN KEY (`script_id`) REFERENCES `script` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='封面图生成产物';
CREATE TABLE `critic_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `role` varchar(20) NOT NULL COMMENT '审核角色: SCRIPT / STORYBOARD',
  `topic_id` bigint DEFAULT NULL,
  `script_id` bigint DEFAULT NULL,
  `content_type` varchar(20) DEFAULT NULL COMMENT 'MYSTERY / BIOGRAPHY_1P / LIFE_COPY',
  `score` int NOT NULL COMMENT '0-100',
  `decision` varchar(16) NOT NULL COMMENT 'PASS / REWRITE',
  `issues_json` text COMMENT '扣分点 JSON 数组',
  `feedback` text COMMENT '给重投用的反馈段',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_role_created` (`role`,`created_at`),
  KEY `idx_topic` (`topic_id`),
  KEY `idx_script` (`script_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='V49: 编剧/摄影自审结果(ScriptCritic / StoryboardCritic),仅记录结构性结果,非 LLM 计费';
CREATE TABLE `director_note_addendum` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `topic_id` bigint NOT NULL COMMENT '所属 topic',
  `role` varchar(20) NOT NULL COMMENT '写入角色: SCRIPT / STORYBOARD / VOICE 等',
  `addendum_text` text NOT NULL COMMENT '该角色"@群"内容,< 500 字,可执行不空话',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_topic_created` (`topic_id`,`created_at`),
  KEY `idx_topic_role` (`topic_id`,`role`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='V50: 导演笔记群聊增量,每个 stage 完成后写一行,下游 stage 渲染 prompt 时读出来';
CREATE TABLE `fact_check_issue` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `script_id` bigint NOT NULL,
  `line_number` int DEFAULT NULL,
  `original_text` text COLLATE utf8mb4_unicode_ci,
  `issue_type` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '与正史矛盾/野史/朝代错误/服饰不符',
  `suggestion` text COLLATE utf8mb4_unicode_ci,
  `severity` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'CRITICAL/MAJOR/MINOR',
  `source_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Grok 联网验证来源',
  `credibility` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'A/B/C',
  `resolved` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_fc_script` (`script_id`),
  CONSTRAINT `fk_fc_script` FOREIGN KEY (`script_id`) REFERENCES `script` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='事实核查问题清单';
CREATE TABLE `genre_stat_snapshot` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `period_start` date NOT NULL COMMENT '统计周期起(含)',
  `period_end` date NOT NULL COMMENT '统计周期止(含)',
  `platform` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'douyin/bilibili/xiaohongshu/...',
  `genre` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '体裁(剧情/科普/历史/...)',
  `vertical` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '垂类 / 二级分类',
  `submission_count` int NOT NULL DEFAULT '0' COMMENT '周期内投稿量',
  `avg_ctr_pct` decimal(5,2) DEFAULT NULL COMMENT '条均点击率,0-100',
  `avg_play_5s_pct` decimal(5,2) DEFAULT NULL COMMENT '条均 5s 完播率,0-100',
  `avg_drop_2s_pct` decimal(5,2) DEFAULT NULL COMMENT '条均 2s 跳出率,0-100',
  `avg_play_seconds` decimal(8,2) DEFAULT NULL COMMENT '条均播放时长(秒)',
  `median_views` bigint DEFAULT NULL COMMENT '播放量中位数',
  `avg_likes` decimal(12,2) DEFAULT NULL COMMENT '条均点赞数',
  `avg_comments` decimal(12,2) DEFAULT NULL COMMENT '条均评论量',
  `avg_shares` decimal(12,2) DEFAULT NULL COMMENT '条均分享量',
  `notes` text COLLATE utf8mb4_unicode_ci,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_period_platform_genre_vertical` (`period_start`,`period_end`,`platform`,`genre`,`vertical`),
  KEY `idx_period_end` (`period_end`),
  KEY `idx_platform_vertical` (`platform`,`vertical`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='体裁/垂类聚合统计快照(投稿作品.xlsx 按周期导入),KpiDrift 体裁基准的数据源';
CREATE TABLE `image_asset` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `shot_id` bigint NOT NULL,
  `model` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'doubao-seedream-5.0-lite/qwen-image/...',
  `file_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `width` int DEFAULT NULL,
  `height` int DEFAULT NULL,
  `seed` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cost_credits` decimal(8,4) DEFAULT NULL,
  `review_score` decimal(5,2) DEFAULT NULL COMMENT '5维度综合分',
  `review_decision` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'PASS/REGENERATE/MANUAL',
  `review_issues` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '手指畸形/朝代不符/...',
  `is_final` tinyint(1) NOT NULL DEFAULT '0',
  `used_protagonist_ref` tinyint(1) NOT NULL DEFAULT '0' COMMENT '生成此图时是否带了 script.protagonist_ref_asset_id 作为 image-to-image reference',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_image_shot` (`shot_id`),
  CONSTRAINT `fk_image_shot` FOREIGN KEY (`shot_id`) REFERENCES `storyboard_shot` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 生图与审查';
CREATE TABLE `pipeline_run` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `topic_id` bigint DEFAULT NULL COMMENT 'BRAINSTORM 时为 NULL（产出新 topic）',
  `script_id` bigint DEFAULT NULL COMMENT 'SCRIPT 阶段为 NULL；之后阶段必填',
  `stage` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BRAINSTORM/SCRIPT/FACTCHECK/STORYBOARD/IMAGEGEN/IMAGEAUDIT',
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/RUNNING/DONE/FAILED/PAUSED/CANCELLED',
  `started_at` datetime DEFAULT NULL,
  `finished_at` datetime DEFAULT NULL,
  `error_msg` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_completed_index` int NOT NULL DEFAULT '0' COMMENT '断点续跑：已完成第几个 item（按 shot_index）',
  `total_items` int NOT NULL DEFAULT '0' COMMENT '本次共要处理多少 item',
  `pause_requested` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1=worker 应在下一 item 前 PAUSED 退出',
  `params_json` text COLLATE utf8mb4_unicode_ci COMMENT '触发参数快照，rerun 用（force/limit/n 等）',
  `triggered_by` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'API/RERUN/RESUME/SCHEDULER',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_run_topic` (`topic_id`),
  KEY `idx_run_script_stage` (`script_id`,`stage`),
  KEY `idx_run_status` (`status`),
  KEY `idx_run_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI pipeline 执行记录';
CREATE TABLE `preset` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '内部 key,如 lifecopy / freeform',
  `display_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'UI 显示名',
  `description` text COLLATE utf8mb4_unicode_ci COMMENT '一句话说明',
  `visibility` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'private' COMMENT 'private=仅 owner 可见,public=任何人可见',
  `owner_name` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '软标记,无鉴权;本地 admin 模式区分私有预设用',
  `input_schema_json` text COLLATE utf8mb4_unicode_ci COMMENT 'JSON Schema 描述 topic.preset_input_json 的字段',
  `brainstorm_prompt_yaml` text COLLATE utf8mb4_unicode_ci,
  `script_prompt_yaml` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `script_critic_prompt_yaml` text COLLATE utf8mb4_unicode_ci,
  `script_critic_threshold` int DEFAULT NULL COMMENT '低于阈值触发重投,典型 80',
  `storyboard_prompt_yaml` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `storyboard_mode` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'FREE' COMMENT 'PRECISE_BY_CUE=必须输出 anchor_cue_indices 严格连续覆盖;FREE=只校验数量',
  `assistant_director_prompt_yaml` text COLLATE utf8mb4_unicode_ci,
  `bgm_mood_prompt_yaml` text COLLATE utf8mb4_unicode_ci,
  `image_config_json` text COLLATE utf8mb4_unicode_ci,
  `voice_config_json` text COLLATE utf8mb4_unicode_ci,
  `bgm_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `composition_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Remotion composition 名,如 StoryHorizontal / StoryVertical',
  `format_width` int NOT NULL,
  `format_height` int NOT NULL,
  `watermark_text` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'NULL=不加水印',
  `hook_segment_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `current_version` int NOT NULL DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  KEY `idx_preset_visibility` (`visibility`),
  KEY `idx_preset_owner` (`owner_name`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='视频形态预设 — 一行描述"一种视频"的所有配方';
CREATE TABLE `preset_asset` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `preset_id` bigint NOT NULL,
  `kind` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'reference_image / sound_effect / ...',
  `local_path` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '相对启动 cwd 的路径,典型 ./storage/preset_assets/private/{preset}/...',
  `uploaded_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_preset_asset_preset` (`preset_id`),
  CONSTRAINT `fk_preset_asset_preset` FOREIGN KEY (`preset_id`) REFERENCES `preset` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Preset 关联的二进制资源,如主角参考图';
CREATE TABLE `preset_version` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `preset_id` bigint NOT NULL,
  `version` int NOT NULL,
  `snapshot_json` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '整个 preset 行的 JSON 快照,可一键回滚',
  `comment` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '可选改动说明',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_preset_version` (`preset_id`,`version`),
  CONSTRAINT `fk_preset_version_preset` FOREIGN KEY (`preset_id`) REFERENCES `preset` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Preset 修改快照,每次 save_as_new_version 写一行';
CREATE TABLE `published_video` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `script_id` bigint DEFAULT NULL COMMENT '软引用 script.id;NULL=未关联本系统脚本',
  `topic_id` bigint DEFAULT NULL COMMENT '软引用 topic.id;通常 = script.topic_id',
  `title` varchar(300) COLLATE utf8mb4_unicode_ci NOT NULL,
  `project_name` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '短名(≤10 字)显示用,跟 topic.project_name 对齐',
  `platform` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'douyin/bilibili/xiaohongshu/shipinhao/...',
  `platform_video_id` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '平台侧 vid;录入时 (platform, vid) 唯一',
  `published_at` datetime NOT NULL,
  `duration_seconds` int DEFAULT NULL,
  `views` bigint NOT NULL DEFAULT '0',
  `likes` bigint NOT NULL DEFAULT '0',
  `comments` bigint NOT NULL DEFAULT '0',
  `shares` bigint NOT NULL DEFAULT '0',
  `retention_pct` decimal(5,2) DEFAULT NULL COMMENT '0-100 平均完播率',
  `avg_play_seconds` decimal(8,2) DEFAULT NULL COMMENT '平均播放时长(秒);某些平台直接给秒数',
  `drop_2s_pct` decimal(5,2) DEFAULT NULL COMMENT '0-100  2s 跳出率;> 30 视为钩子失败',
  `play_5s_pct` decimal(5,2) DEFAULT NULL COMMENT '0-100  5s 完播率;hook_ctr 的更稳代理',
  `avg_play_ratio_pct` decimal(5,2) DEFAULT NULL COMMENT '0-100  平均播放占比 = avg_play / duration',
  `favorite_rate_pct` decimal(5,2) DEFAULT NULL COMMENT '0-100  收藏率 = favorites / views',
  `dislike_rate_pct` decimal(5,2) DEFAULT NULL COMMENT '0-100  不感兴趣率;高=触发负反馈',
  `hook_ctr` decimal(5,2) DEFAULT NULL COMMENT '0-100 钩子点击率(3s 留存)',
  `cost_yuan` decimal(10,4) DEFAULT NULL COMMENT '该条总成本(LLM+图+音+视频);手填或脚本聚合',
  `hook_template` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '反转型/密信型/问句型/...',
  `notes` text COLLATE utf8mb4_unicode_ci,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `cover_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '封面图 URL(列表展示缩略图,抖音 cover.url_list[0])',
  `like_rate` decimal(7,5) DEFAULT NULL COMMENT '点赞率(0~1 浮点 → 这里存原值;前端展示 ×100%)',
  `share_rate` decimal(7,5) DEFAULT NULL COMMENT '分享率(同上)',
  `comment_rate` decimal(7,5) DEFAULT NULL COMMENT '评论率(同上)',
  `subscribe_count` int DEFAULT NULL COMMENT '该视频带来的涨粉数',
  `unsubscribe_count` int DEFAULT NULL COMMENT '该视频带来的掉粉数',
  `cover_ctr` decimal(5,2) DEFAULT NULL COMMENT '封面点击率(0~100 标准百分数)',
  `homepage_visit_count` int DEFAULT NULL COMMENT '主页访问次数',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_platform_published_title` (`platform`,`published_at`,`title`(100)),
  UNIQUE KEY `uk_platform_vid` (`platform`,`platform_video_id`),
  KEY `idx_published_at` (`published_at`),
  KEY `idx_script_id` (`script_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='已发布视频指标(手填或后续 OAuth 自动采集),驱动数据复盘看板';
CREATE TABLE `script` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `topic_id` bigint NOT NULL,
  `version` int NOT NULL DEFAULT '1',
  `model_used` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'claude-opus-4-7/deepseek-v3.2/...',
  `word_count` int DEFAULT NULL,
  `duration_seconds` int DEFAULT NULL,
  `full_text` mediumtext COLLATE utf8mb4_unicode_ci,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/REVIEWING/APPROVED/REJECTED',
  `review_score` decimal(5,2) DEFAULT NULL,
  `protagonist_ref_asset_id` bigint DEFAULT NULL COMMENT '该 script 的主角基准照 asset id，首张 PASS 时锁定，后续生图作为 image-to-image reference',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `bgm_mood_tag` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'LLM 给本 script 打的 mood, 6 词表之一',
  PRIMARY KEY (`id`),
  KEY `idx_script_topic` (`topic_id`),
  KEY `fk_script_protagonist_ref` (`protagonist_ref_asset_id`),
  CONSTRAINT `fk_script_protagonist_ref` FOREIGN KEY (`protagonist_ref_asset_id`) REFERENCES `image_asset` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_script_topic` FOREIGN KEY (`topic_id`) REFERENCES `topic` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='脚本（多版本）';
CREATE TABLE `script_bgm_choice` (
  `script_id` bigint NOT NULL,
  `bgm_track_id` bigint NOT NULL,
  `volume` decimal(3,2) NOT NULL DEFAULT '0.25' COMMENT '渲染时 BGM 音量, 0.05~0.6',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`script_id`),
  KEY `idx_sbc_track` (`bgm_track_id`),
  CONSTRAINT `fk_sbc_script` FOREIGN KEY (`script_id`) REFERENCES `script` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sbc_track` FOREIGN KEY (`bgm_track_id`) REFERENCES `bgm_track` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='script 选定的 BGM(1:1)';
CREATE TABLE `script_section` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `script_id` bigint NOT NULL,
  `section_code` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'A/B/C/D/E',
  `title` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '钩子段/信息累积/揭秘前奏/高潮揭秘/余韵',
  `start_seconds` int DEFAULT NULL,
  `end_seconds` int DEFAULT NULL,
  `text_content` text COLLATE utf8mb4_unicode_ci,
  `director_note` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_golden_line` tinyint(1) NOT NULL DEFAULT '0' COMMENT '金句独占帧',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_section_script` (`script_id`),
  CONSTRAINT `fk_section_script` FOREIGN KEY (`script_id`) REFERENCES `script` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='脚本五段结构';
CREATE TABLE `series` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cover_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_series_slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系列（民国奇案 / 明朝悬案……）';
CREATE TABLE `series_hook` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `from_topic_id` bigint NOT NULL COMMENT '本集',
  `from_script_id` bigint DEFAULT NULL COMMENT '钩子从哪条 script 的 E 段抽出来的(观测冗余字段)',
  `dismissed_at` datetime DEFAULT NULL COMMENT '人工标记忽略的时间,NULL=未处理。软删,banner 查询会排除非 NULL',
  `to_topic_id` bigint DEFAULT NULL COMMENT '下集（确认后填）',
  `hook_text` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '本集结尾下集种子',
  `next_episode_hint` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '下集预告 1-2 句',
  `strength` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'WEAK' COMMENT 'STRONG=点名具体人/事/谜,值得兑现;WEAK=空钩(下期再聊)',
  `suggested_title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'LLM 根据钩子建议的下集 topic 草稿标题',
  `suggested_dynasty` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'LLM 根据钩子推断的下集朝代',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hook_from` (`from_topic_id`),
  KEY `idx_hook_to` (`to_topic_id`),
  KEY `idx_strength_unresolved` (`strength`,`to_topic_id`,`dismissed_at`),
  CONSTRAINT `fk_hook_from` FOREIGN KEY (`from_topic_id`) REFERENCES `topic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hook_to` FOREIGN KEY (`to_topic_id`) REFERENCES `topic` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='追更钩子（本集→下集种子）';
CREATE TABLE `storyboard_shot` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `script_id` bigint NOT NULL,
  `shot_index` int NOT NULL,
  `section_code` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '锚回 script_section.section_code',
  `time_range` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '0-3s',
  `duration_seconds` decimal(5,2) DEFAULT NULL,
  `prompt_zh` text COLLATE utf8mb4_unicode_ci,
  `prompt_en` text COLLATE utf8mb4_unicode_ci,
  `negative_prompt` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `style_tag` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shot_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '远景/中景/特写/极特写/空镜',
  `seed` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `anchor_text` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'V46.5:LLM 标记的脚本字面锚定短语;后端 validate 必须出现在 script.full_text 中',
  `anchor_match` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'V46.5:后端校验 anchor_text 是否命中 script.full_text;false=未命中,该镜画面可能跟字幕对不上',
  `anchor_cue_start` int DEFAULT NULL COMMENT 'V47.0:该 shot 对应的 SRT cue 起始序号(1 起,inclusive)。NULL = 未走 PRECISE_BY_CUE',
  `anchor_cue_end` int DEFAULT NULL COMMENT 'V47.0:该 shot 对应的 SRT cue 结束序号(1 起,inclusive)。NULL = 未走 PRECISE_BY_CUE',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_shot_script_index` (`script_id`,`shot_index`),
  KEY `idx_shot_script` (`script_id`),
  KEY `idx_shot_script_section` (`script_id`,`section_code`),
  CONSTRAINT `fk_shot_script` FOREIGN KEY (`script_id`) REFERENCES `script` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='分镜镜头（30-50/脚本）';
CREATE TABLE `topic` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `title` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `project_name` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '项目名(显示用,默认 LEFT(title,10),可手改)',
  `dynasty` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '朝代标签（明/清/民国/...）',
  `genre` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '题材（宫廷/案件/灵异/...）',
  `protagonist` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主角描述',
  `hook_type` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '钩子类型（反逻辑/数字冲击/...）',
  `emotion` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '情绪基调',
  `duration_minutes` int DEFAULT NULL,
  `potential_score` decimal(5,2) DEFAULT NULL COMMENT '潜力分（0-100）',
  `historical_reference` text COLLATE utf8mb4_unicode_ci COMMENT '史料引用',
  `series_id` bigint DEFAULT NULL COMMENT '已确认归属的 series.id',
  `ai_suggested_series` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'LLM 输出的系列名（待 resolve 到 series_id）',
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/SCHEDULED/PRODUCED/PUBLISHED/ARCHIVED',
  `source` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'AI_BRAINSTORM' COMMENT 'AI_BRAINSTORM/MANUAL/RECYCLE',
  `source_hook_id` bigint DEFAULT NULL COMMENT 'fulfill 时记录来自哪条 series_hook;NULL=非钩子来源(brainstorm / 手建)。允许 hook 后续被删,FK 不级联',
  `notes` text COLLATE utf8mb4_unicode_ci,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `protagonist_ref_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '第一视角主角基准图 URL(Doubao CDN 直链);ImageGen 在 script.protagonist_ref_asset_id 缺失时回退用',
  `director_note` json DEFAULT NULL COMMENT '总导演 LLM 产出的导演笔记,BIOGRAPHY_1P 用',
  `preset_id` bigint NOT NULL COMMENT 'P3 后必填:关联 preset.id,所有 service 走 preset 单一路径',
  `preset_input_json` text COLLATE utf8mb4_unicode_ci COMMENT '用户填的字段,与 preset.input_schema_json 对应;替代旧 identity_card_json/persona_json',
  `preset_version_used` int DEFAULT NULL COMMENT '本 topic 跑流水线时使用的 preset 版本号,用于历史复现',
  PRIMARY KEY (`id`),
  KEY `idx_topic_status` (`status`),
  KEY `idx_topic_score` (`potential_score`),
  KEY `idx_topic_series` (`series_id`),
  KEY `idx_source_hook_id` (`source_hook_id`),
  KEY `idx_topic_preset` (`preset_id`),
  CONSTRAINT `fk_topic_preset` FOREIGN KEY (`preset_id`) REFERENCES `preset` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_topic_series` FOREIGN KEY (`series_id`) REFERENCES `series` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='选题候选 / 已排期 / 已制作 / 已发布';
CREATE TABLE `video_asset` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `script_id` bigint NOT NULL,
  `voice_asset_id` bigint DEFAULT NULL COMMENT '本次渲染采用的 voice_asset, NULL 表示无配音',
  `video_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `duration_seconds` int DEFAULT NULL,
  `width` int DEFAULT NULL,
  `height` int DEFAULT NULL,
  `format` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '9:16/16:9/1:1 等成片比例标签',
  `shot_count` int DEFAULT NULL COMMENT '采用的镜头数,审计用',
  `cost_yuan` decimal(8,4) DEFAULT NULL,
  `is_final` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `bgm_track_id` bigint DEFAULT NULL COMMENT '渲染时采用的 bgm_track, NULL 表示无 BGM',
  `bgm_volume` decimal(3,2) DEFAULT NULL COMMENT '渲染时实际使用的 BGM 音量',
  `timing_strategy` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '对齐策略: PRECISE_BY_SECTION | UNIFORM_SCALE | RAW',
  `timing_note` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '对齐策略详情(strategy + reason)',
  PRIMARY KEY (`id`),
  KEY `fk_video_asset_voice` (`voice_asset_id`),
  KEY `idx_video_script_created` (`script_id`,`created_at`),
  KEY `idx_video_bgm` (`bgm_track_id`),
  CONSTRAINT `fk_video_asset_script` FOREIGN KEY (`script_id`) REFERENCES `script` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_video_asset_voice` FOREIGN KEY (`voice_asset_id`) REFERENCES `voice_asset` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='视频合成产物';
CREATE TABLE `voice_asset` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `script_id` bigint NOT NULL,
  `model` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'TTS 模型/音色 id, e.g. azure-zh-male-1',
  `voice_label` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '可读音色名,展示用',
  `speed` decimal(3,1) NOT NULL DEFAULT '1.0',
  `pitch` int NOT NULL DEFAULT '0',
  `subtitle_style` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'standard' COMMENT 'standard/highlight/karaoke',
  `audio_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'mp3/wav 产物 URL',
  `subtitle_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'srt/ass 字幕 URL',
  `duration_seconds` int DEFAULT NULL,
  `cost_yuan` decimal(8,4) DEFAULT NULL,
  `is_final` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1=该 script 当前选中的定稿配音',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_voice_script_created` (`script_id`,`created_at`),
  CONSTRAINT `fk_voice_asset_script` FOREIGN KEY (`script_id`) REFERENCES `script` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='脚本配音/字幕产物';
CREATE TABLE `weekly_review` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `week_code` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'W22',
  `period_start` date NOT NULL,
  `period_end` date NOT NULL,
  `new_followers` int DEFAULT NULL,
  `avg_completion` decimal(5,2) DEFAULT NULL,
  `what_text` text COLLATE utf8mb4_unicode_ci COMMENT 'What 数据归因',
  `so_what_text` text COLLATE utf8mb4_unicode_ci COMMENT 'So What 影响判断',
  `now_what_text` text COLLATE utf8mb4_unicode_ci COMMENT 'Now What 下周动作',
  `highlights` text COLLATE utf8mb4_unicode_ci COMMENT '本周亮点 ?',
  `lessons` text COLLATE utf8mb4_unicode_ci COMMENT '教训 ⚠️',
  `experiments` text COLLATE utf8mb4_unicode_ci COMMENT '试错 ?',
  `next_week` text COLLATE utf8mb4_unicode_ci COMMENT '下周改进 ?',
  `insight` text COLLATE utf8mb4_unicode_ci,
  `next_actions` text COLLATE utf8mb4_unicode_ci,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_review_week` (`week_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='每周复盘报告';

SET FOREIGN_KEY_CHECKS = 1;

-- ---------------------------------------------------------------------
-- app_config 默认行(value 留空,启动后端后到前端「系统设置」UI 填写)
-- 用 INSERT IGNORE:V1 万一被重跑也只补缺失的 key,不会覆盖已有 value
-- ---------------------------------------------------------------------
INSERT IGNORE INTO app_config (config_key, description, is_secret, category, sort_order) VALUES
  ('auteur.llm.base-url',                'LLM 中转站 base URL,如 https://relay.example.com/v1',                0, 'llm', 10),
  ('auteur.llm.api-key',                 'LLM 中转站 API Key',                                                  1, 'llm', 20),
  ('auteur.llm.default-model',           '默认模型 ID,如 DeepSeek-V3.2 / claude-opus-4-7',                     0, 'llm', 30),

  ('auteur.tos.endpoint',                '火山 TOS endpoint,如 tos-cn-beijing.volces.com',                    0, 'tos', 10),
  ('auteur.tos.region',                  '火山 TOS region,如 cn-beijing',                                      0, 'tos', 20),
  ('auteur.tos.access-key',              '火山 TOS Access Key',                                                 1, 'tos', 30),
  ('auteur.tos.secret-key',              '火山 TOS Secret Key',                                                 1, 'tos', 40),
  ('auteur.tos.bucket',                  '火山 TOS Bucket 名',                                                  0, 'tos', 50),

  ('auteur.voice.volcano.api-key',       '火山豆包语音 X-Api-Key',                                              1, 'voice', 20),
  ('auteur.voice.volcano.app-key',       '火山豆包语音 X-Api-App-Id(异步任务用)',                              1, 'voice', 30),
  ('auteur.voice.volcano.access-key',    '火山豆包语音 X-Api-Access-Key(异步任务用)',                         1, 'voice', 40),
  ('auteur.voice.volcano.resource-id',   'X-Api-Resource-Id,如 seed-tts-2.0',                                 0, 'voice', 50),

  ('auteur.bgm.jamendo.client-id',       'Jamendo 选曲 client_id(免费注册 https://devportal.jamendo.com/)',   1, 'bgm', 10),

  ('auteur.extension.token',             '浏览器插件回写 X-Extension-Token 校验值',                              1, 'extension', 10);

-- 两个非 secret 的公共默认值;COALESCE 保证已有非空 value 时不被覆盖
UPDATE app_config SET config_value = COALESCE(NULLIF(config_value, ''), 'tos-cn-beijing.volces.com') WHERE config_key = 'auteur.tos.endpoint';
UPDATE app_config SET config_value = COALESCE(NULLIF(config_value, ''), 'cn-beijing')                WHERE config_key = 'auteur.tos.region';
